project_id = "hwkcqgmtinbgyjjgcgmp"

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.migrate-images]
verify_jwt = false
