project_id = "hwkcqgmtinbgyjjgcgmp"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-setup-service]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.migrate-images]
verify_jwt = false

[functions.paystack-list-banks]
verify_jwt = false

[functions.paystack-create-subaccount]
verify_jwt = false

[functions.stroke-my-shop]
verify_jwt = false

[functions.know-this-shop]
verify_jwt = false

[functions.marketing-ai-assist]
verify_jwt = false
